 app/components/chat/BaseChat.tsx           |   1 [32m+[m
 app/components/chat/ClassificationCard.tsx |  42 [32m++++++++[m[31m-[m
 app/entry.server.tsx                       |  10 [32m+[m[31m-[m
 app/lib/auth/session.ts                    |  23 [32m+++[m[31m--[m
 app/lib/auth/supabase-cookies.ts           |   6 [32m+[m[31m-[m
 app/lib/hooks/useQHubPromptSeed.ts         |   7 [32m+[m[31m-[m
 app/lib/modules/llm/providers/anthropic.ts |  12 [32m++[m[31m-[m
 app/lib/persistence/useChatHistory.ts      |   1 [32m+[m
 app/lib/qhub/classification-rules.ts       |  78 [32m++++++++++[m[31m-----[m
 app/lib/qhub/classification.ts             |   3 [32m+[m[31m-[m
 app/lib/qhub/classifier.server.ts          |  89 [32m++++++++++[m[31m-------[m
 app/lib/qhub/governance-service.server.ts  |  10 [32m+[m[31m-[m
 app/lib/qhub/governance.ts                 |  38 [32m++++[m[31m----[m
 app/lib/qhub/messenger.ts                  |  13 [32m+[m[31m--[m
 app/lib/qhub/policy-catalog.ts             |  12 [32m+[m[31m--[m
 app/lib/qhub/policy-engine.ts              |   8 [32m+[m[31m-[m
 app/lib/qhub/qhub-app.server.ts            |   8 [32m+[m[31m-[m
 app/lib/qhub/session-id.server.ts          |   5 [32m+[m[31m-[m
 app/lib/stores/workbench.ts                |  70 [32m++++++++[m[31m------[m
 app/root.tsx                               |  13 [32m++[m[31m-[m
 app/routes/_index.tsx                      |   5 [32m+[m[31m-[m
 app/routes/api.chat.ts                     |  19 [32m++[m[31m--[m
 app/routes/api.llmcall.ts                  |   6 [32m+[m[31m-[m
 app/routes/auth.callback.tsx               |  15 [32m++[m[31m-[m
 app/routes/login.tsx                       |  15 [32m++[m[31m-[m
 app/test/classification.test.ts            |   6 [32m+[m[31m-[m
 app/test/governance.test.ts                | 147 [32m+++++++++++++++++++[m[31m----------[m
 app/test/policy-engine.test.ts             |   6 [32m+[m[31m-[m
 app/test/policy-governance.test.ts         |   4 [32m+[m[31m-[m
 29 files changed, 425 insertions(+), 247 deletions(-)
