-- QHUB Application Identity Table
-- Migration: 20260723_qhub_applications
--
-- PURPOSE: Provides a permanent Quantex-owned identity for every AI-built app
-- that passes through QHUB Studio. This record is independent of Bolt's chatId,
-- urlId, and conversationId — those are builder-engine implementation details
-- that may change. qhub_app_id is the stable Quantex identity.
--
-- ALSO: Stores chain_id durably after CHAIN_GENESIS is accepted by the Lambda.
-- This replaces the in-memory chainIdCache which was lost on process restart,
-- redeployment, and Cloudflare isolate recycling.
--
-- Run this in your Supabase SQL editor (project dashboard → SQL editor → New query).

CREATE TABLE IF NOT EXISTS qhub_applications (
  -- Permanent Quantex-owned identifier. UUIDv4, generated by QHUB Studio server.
  -- This is the app_id sent to the Lambda and stored in the governance chain.
  qhub_app_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Tenant / org identifier from the authenticated server session.
  -- Maps to client_id in the Lambda event body.
  org_id              TEXT NOT NULL,

  -- The authenticated user who created this application record.
  created_by          TEXT NOT NULL,

  -- Builder engine that originated this application.
  builder_engine      TEXT NOT NULL DEFAULT 'qhub-studio',

  -- Bolt.diy's urlId (set after first artifact is created). May be null initially.
  builder_project_id  TEXT,

  -- Bolt.diy's chat identifier.
  conversation_id     TEXT,

  -- Optional workspace identifier (for future multi-workspace support).
  workspace_id        TEXT,

  -- chain_id returned by the Lambda after a successful CHAIN_GENESIS event.
  -- NULL until genesis is committed. Set exactly once.
  -- This is the authoritative durable source of chain_id — replaces in-memory cache.
  chain_id            UUID,

  -- Current risk tier (mirrors the latest CLASSIFICATION_ASSIGNED event).
  risk_tier           TEXT NOT NULL DEFAULT 'UNCLASSIFIED'
                      CHECK (risk_tier IN ('UNCLASSIFIED', 'T0', 'T1', 'T2', 'T3')),

  -- Governance lifecycle status.
  governance_status   TEXT NOT NULL DEFAULT 'pending'
                      CHECK (governance_status IN ('pending', 'genesis_committed', 'submitted', 'classified', 'attested', 'deployed', 'rejected')),

  -- Timestamps.
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast lookup by conversation_id (used at every AI model invocation).
CREATE INDEX IF NOT EXISTS idx_qhub_apps_conversation_id
  ON qhub_applications (conversation_id)
  WHERE conversation_id IS NOT NULL;

-- Index for fast lookup by org_id (used for Governance Console listing).
CREATE INDEX IF NOT EXISTS idx_qhub_apps_org_id
  ON qhub_applications (org_id);

-- Index for fast lookup by builder_project_id (urlId from bolt.diy).
CREATE INDEX IF NOT EXISTS idx_qhub_apps_builder_project_id
  ON qhub_applications (builder_project_id)
  WHERE builder_project_id IS NOT NULL;

-- Auto-update updated_at on any row modification.
CREATE OR REPLACE FUNCTION update_qhub_applications_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_qhub_applications_updated_at
  BEFORE UPDATE ON qhub_applications
  FOR EACH ROW EXECUTE FUNCTION update_qhub_applications_updated_at();

-- Row-Level Security: each tenant can only read/write their own applications.
-- Service-role key bypasses RLS (used by GovernanceService server module).
ALTER TABLE qhub_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY qhub_applications_tenant_isolation ON qhub_applications
  USING (org_id = current_setting('app.org_id', true));

-- Comment: The service role (SUPABASE_SERVICE_ROLE_KEY) bypasses RLS.
-- GovernanceService uses the service role key for all writes.
-- The RLS policy protects against direct database access from the anon key.
