/* eslint-disable @typescript-eslint/naming-convention -- pre-existing DB-mapped snake_case / private-method naming; unrelated to R6 (module is only annotated with __QHUB_MODULE_CLASSIFICATION) */
/**
 * QHUB Application Identity — SERVER ONLY
 * app/lib/qhub/qhub-app.server.ts
 *
 * Manages the permanent Quantex-owned identity for every AI-built application
 * that passes through QHUB Studio. This identity is independent of Bolt's
 * ephemeral identifiers (chatId, urlId, conversationId).
 *
 * KEY CONCEPTS:
 *   qhub_app_id — UUIDv4 generated by this module. This is the stable Quantex
 *                 identity and is the app_id sent to the Lambda in all events.
 *
 *   chain_id    — UUIDv4 returned by the Lambda after a successful CHAIN_GENESIS
 *                 event. Stored durably in Supabase. This replaces the in-memory
 *                 chainIdCache from prior versions, which was not durable across
 *                 process restart, redeployment, or Cloudflare isolate recycling.
 *
 * PERSISTENCE:
 *   Primary store: Supabase (qhub_applications table — see migrations/).
 *   In-memory cache: module-level Map for warm reads. The DB is always the
 *   source of truth; the cache is an optimization only.
 *
 * REQUIRED ENV VARS (server-side only):
 *   SUPABASE_URL              Quantex Supabase project URL
 *   SUPABASE_SERVICE_ROLE_KEY Service role key — bypasses RLS, never expose to browser
 */

import { createHash } from 'node:crypto';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { ClassificationResult, PersistedRiskTier } from './classification';
import type { PolicyProfile, PolicyStatus } from './policy';
import { isSchemaMissingError } from './schema-contract';

/**
 * Raised when a persistence call hits a MISSING schema object (table/column).
 * This is the fail-closed replacement for the previous behaviour of logging
 * "run the classification migration" and continuing — which masked a
 * project/schema mismatch during Gate 03 live closure.
 */
export class SchemaMissingError extends Error {
  readonly supabaseCode?: string;

  constructor(operation: string, object: string, code?: string) {
    super(
      `[QhubApp] ${operation} failed closed: required schema object "${object}" is missing from the connected ` +
        `Supabase project${code ? ` (${code})` : ''}. Apply the pending migration before serving governance traffic.`,
    );
    this.name = 'SchemaMissingError';
    this.supabaseCode = code;
  }
}

// ─── Types ────────────────────────────────────────────────────────────────────

export interface QhubAppRecord {
  qhub_app_id: string;
  org_id: string;
  created_by: string;
  builder_engine: string;
  builder_project_id: string | null;
  conversation_id: string | null;
  workspace_id: string | null;
  chain_id: string | null;
  risk_tier: string;
  classification: ClassificationResult | null;
  governance_status: string;
  created_at: string;
  updated_at: string;
}

export interface CreateQhubAppParams {
  orgId: string;
  userId: string;
  conversationId: string;

  /** bolt.diy urlId — may be null initially, filled in once first artifact is created */
  builderProjectId?: string;
}

/*
 * ─── In-memory cache (optimization — DB is authoritative) ─────────────────────
 * Keyed by conversationId → QhubAppRecord
 * Invalidated on chain_id write and updated_at change.
 */

const appCache = new Map<string, QhubAppRecord>();

// ─── Supabase client factory (service role — server only) ─────────────────────

function getSupabaseAdmin(env: Record<string, string | undefined>): SupabaseClient {
  const url = env.SUPABASE_URL ?? process.env.SUPABASE_URL ?? '';
  const serviceKey = env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_SERVICE_ROLE_KEY ?? '';

  if (!url || !serviceKey) {
    throw new Error('[QhubApp] SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required for durable persistence.');
  }

  return createClient(url, serviceKey, {
    auth: { persistSession: false },
  });
}

// ─── Create or retrieve existing QHUB app for a conversation ─────────────────

/**
 * Get or create the QHUB application record for a given conversation.
 *
 * Idempotent: if a record already exists for this conversationId, returns it.
 * Otherwise creates a new record with a fresh qhub_app_id.
 *
 * The returned qhub_app_id is the stable app_id to use in all Lambda events.
 */
export async function getOrCreateQhubApp(
  params: CreateQhubAppParams,
  env: Record<string, string | undefined>,
): Promise<QhubAppRecord> {
  const { conversationId, orgId, userId, builderProjectId } = params;

  // 1. Hot cache hit
  const cached = appCache.get(conversationId);

  if (cached) {
    return cached;
  }

  const sb = getSupabaseAdmin(env);

  // 2. DB lookup by conversationId
  const { data: existing, error: lookupErr } = await sb
    .from('qhub_applications')
    .select('*')
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId)
    .maybeSingle();

  if (lookupErr) {
    throw new Error(`[QhubApp] DB lookup failed: ${lookupErr.message}`);
  }

  if (existing) {
    // Update builderProjectId if it was null and now available
    if (!existing.builder_project_id && builderProjectId) {
      const { data: updated } = await sb
        .from('qhub_applications')
        .update({ builder_project_id: builderProjectId })
        .eq('qhub_app_id', existing.qhub_app_id)
        .select()
        .single();

      const record = (updated ?? existing) as QhubAppRecord;
      appCache.set(conversationId, record);

      return record;
    }

    appCache.set(conversationId, existing as QhubAppRecord);

    return existing as QhubAppRecord;
  }

  // 3. Create new record
  const { data: created, error: createErr } = await sb
    .from('qhub_applications')
    .insert({
      org_id: orgId,
      created_by: userId,
      builder_engine: 'qhub-studio',
      builder_project_id: builderProjectId ?? null,
      conversation_id: conversationId,
      governance_status: 'pending',
    })
    .select()
    .single();

  if (createErr || !created) {
    throw new Error(`[QhubApp] DB insert failed: ${createErr?.message ?? 'no data returned'}`);
  }

  const record = created as QhubAppRecord;
  appCache.set(conversationId, record);

  console.log(`[QhubApp] Created app record qhub_app_id=${record.qhub_app_id} for conversation=${conversationId}`);

  return record;
}

// ─── Persist chain_id after successful genesis ─────────────────────────────────

/**
 * Store the chain_id returned by Lambda after a successful CHAIN_GENESIS event.
 * Marks governance_status = 'genesis_committed'.
 *
 * This is the authoritative write that replaces the in-memory chainIdCache.
 * Must be called immediately after Lambda returns chain_id.
 */
export async function persistChainId(
  qhubAppId: string,
  chainId: string,
  env: Record<string, string | undefined>,
): Promise<void> {
  const sb = getSupabaseAdmin(env);

  const { error } = await sb
    .from('qhub_applications')
    .update({ chain_id: chainId, governance_status: 'genesis_committed' })
    .eq('qhub_app_id', qhubAppId)
    .is('chain_id', null); // Only write once — chain_id is immutable after genesis

  if (error) {
    /*
     * Log but do not throw — the event was already written to Lambda/DynamoDB.
     * The chain is intact; only our local record is incomplete.
     */
    console.error(`[QhubApp] Failed to persist chain_id for qhub_app_id=${qhubAppId}: ${error.message}`);
    return;
  }

  // Invalidate cache entry so next read fetches the updated record
  for (const [convId, record] of appCache.entries()) {
    if (record.qhub_app_id === qhubAppId) {
      appCache.delete(convId);
      break;
    }
  }

  console.log(`[QhubApp] chain_id persisted for qhub_app_id=${qhubAppId}`);
}

// ─── Read chain_id (durable, with cache) ──────────────────────────────────────

/**
 * Retrieve the chain_id for a given conversationId.
 * Returns null if genesis has not yet been committed.
 *
 * Read order: memory cache → Supabase DB.
 */
export async function getChainId(
  conversationId: string,
  orgId: string,
  env: Record<string, string | undefined>,
): Promise<string | null> {
  // Cache hit
  const cached = appCache.get(conversationId);

  if (cached) {
    return cached.chain_id;
  }

  // DB read
  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_applications')
    .select('qhub_app_id, chain_id')
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId)
    .maybeSingle();

  if (error) {
    console.error(`[QhubApp] getChainId DB read failed: ${error.message}`);
    return null;
  }

  return data?.chain_id ?? null;
}

// ─── Update builderProjectId (called when urlId becomes available) ─────────────

/**
 * Update the builderProjectId (bolt.diy urlId) on an existing record.
 * Called from Chat.client.tsx when urlId is first set.
 */
export async function updateBuilderProjectId(
  conversationId: string,
  orgId: string,
  builderProjectId: string,
  env: Record<string, string | undefined>,
): Promise<void> {
  const sb = getSupabaseAdmin(env);
  const { error } = await sb
    .from('qhub_applications')
    .update({ builder_project_id: builderProjectId })
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId);

  if (error) {
    console.error(`[QhubApp] updateBuilderProjectId failed: ${error.message}`);
  } else {
    // Invalidate cache
    appCache.delete(conversationId);
  }
}

// ─── Gate 02: classification persistence ──────────────────────────────────────

/**
 * Persist the current classification and its risk tier on the app record.
 * The immutable ledger (CLASSIFICATION_ASSIGNED events) remains the authoritative
 * history; this row holds only the CURRENT classification for fast reads.
 * Marks governance_status = 'classified'.
 */
export async function persistClassification(
  qhubAppId: string,
  classification: ClassificationResult,
  env: Record<string, string | undefined>,
): Promise<void> {
  const sb = getSupabaseAdmin(env);

  /*
   * Write the tier first (columns that always exist since 20260723) so
   * subsequent events get the real tier. A schema-missing error here means the
   * base table itself is absent — fail closed rather than continue.
   */
  const { error: tierErr } = await sb
    .from('qhub_applications')
    .update({ risk_tier: classification.risk_tier, governance_status: 'classified' })
    .eq('qhub_app_id', qhubAppId);

  if (tierErr) {
    if (isSchemaMissingError(tierErr)) {
      throw new SchemaMissingError('persistClassification', 'qhub_applications', tierErr.code);
    }

    /*
     * Non-schema (transient/permission) error — surface it; the snapshot below
     * is what policy assignment reads, so a partial write must not look like success.
     */
    throw new Error(`[QhubApp] persistClassification tier write failed for ${qhubAppId}: ${tierErr.message}`);
  }

  /*
   * Then the full snapshot (requires the 20260725_qhub_classification migration).
   * FAIL CLOSED when the `classification` column is absent: the previous code
   * logged "run the classification migration" and continued, which silently
   * degraded the governance record and masked a project/schema mismatch.
   */
  const { error: jsonErr } = await sb.from('qhub_applications').update({ classification }).eq('qhub_app_id', qhubAppId);

  if (jsonErr) {
    if (isSchemaMissingError(jsonErr)) {
      throw new SchemaMissingError('persistClassification', 'qhub_applications.classification', jsonErr.code);
    }

    throw new Error(`[QhubApp] persistClassification snapshot write failed for ${qhubAppId}: ${jsonErr.message}`);
  }

  // Invalidate cache so subsequent events read the new tier.
  for (const [convId, record] of appCache.entries()) {
    if (record.qhub_app_id === qhubAppId) {
      appCache.delete(convId);
      break;
    }
  }

  console.log(
    `[QhubApp] classification persisted qhub_app_id=${qhubAppId} risk_tier=${classification.risk_tier} v=${classification.classification_version}`,
  );
}

/** Read the current persisted classification (for versioning / gate checks). */
export async function getClassification(
  qhubAppId: string,
  env: Record<string, string | undefined>,
): Promise<ClassificationResult | null> {
  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_applications')
    .select('classification')
    .eq('qhub_app_id', qhubAppId)
    .maybeSingle();

  if (error) {
    /*
     * FAIL CLOSED when the `classification` column is absent. Returning null on
     * a missing column would look identical to "not yet classified", letting
     * policy assignment proceed against an unmigrated project. A genuine
     * missing column must block the flow, not silently read as unclassified.
     */
    if (isSchemaMissingError(error)) {
      throw new SchemaMissingError('getClassification', 'qhub_applications.classification', error.code);
    }

    console.error(`[QhubApp] getClassification failed for ${qhubAppId}: ${error.message}`);

    return null;
  }

  return (data?.classification as ClassificationResult | null) ?? null;
}

/**
 * Read the persisted risk tier for the app of a given conversation.
 * Returns 'UNCLASSIFIED' until a classification has been confirmed.
 * Used so genesis / AI_MODEL_INVOKED / gate events carry the REAL tier.
 */
export async function getPersistedRiskTier(
  conversationId: string,
  orgId: string,
  env: Record<string, string | undefined>,
): Promise<PersistedRiskTier> {
  const cached = appCache.get(conversationId);

  if (cached?.risk_tier) {
    return (cached.risk_tier as PersistedRiskTier) ?? 'UNCLASSIFIED';
  }

  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_applications')
    .select('risk_tier')
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId)
    .maybeSingle();

  if (error) {
    console.error(`[QhubApp] getPersistedRiskTier failed: ${error.message}`);
    return 'UNCLASSIFIED';
  }

  return ((data?.risk_tier as PersistedRiskTier) ?? 'UNCLASSIFIED') || 'UNCLASSIFIED';
}

// ─── Gate 03 Phase 0: classification proposals (server-authoritative) ─────────

export interface ClassificationProposal {
  proposal_id: string;
  org_id: string;
  conversation_id: string | null;
  qhub_app_id: string | null;
  description_hash: string;
  provisional: ClassificationResult;
  risk_floor: string;
  ai_proposed_tier: string;
  classifier_version: string;
  created_by: string;
  created_at: string;
  expires_at: string;
  status: 'PENDING' | 'CONSUMED' | 'EXPIRED';
}

const PROPOSAL_TTL_MIN = 30;

/**
 * Persist a provisional classification and return its proposal_id.
 * The browser never sees the authoritative signals again — only the id.
 */
export async function persistProposal(
  params: {
    orgId: string;
    conversationId: string;
    description: string;
    provisional: ClassificationResult;
    createdBy: string;
  },
  env: Record<string, string | undefined>,
): Promise<string> {
  const sb = getSupabaseAdmin(env);
  const description_hash = createHash('sha256').update(params.description).digest('hex');
  const expires_at = new Date(Date.now() + PROPOSAL_TTL_MIN * 60_000).toISOString();

  const { data, error } = await sb
    .from('qhub_classification_proposals')
    .insert({
      org_id: params.orgId,
      conversation_id: params.conversationId,
      description_hash,
      provisional: params.provisional,
      risk_floor: params.provisional.risk_floor,
      ai_proposed_tier: params.provisional.ai_proposed_tier,
      classifier_version: params.provisional.classifier_version,
      created_by: params.createdBy,
      expires_at,
    })
    .select('proposal_id')
    .single();

  if (error || !data) {
    throw new Error(`[QhubApp] persistProposal failed: ${error?.message ?? 'no id'}`);
  }

  return data.proposal_id as string;
}

/** Load a proposal (server-authoritative). Returns null if not found. */
export async function getProposal(
  proposalId: string,
  env: Record<string, string | undefined>,
): Promise<ClassificationProposal | null> {
  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_classification_proposals')
    .select('*')
    .eq('proposal_id', proposalId)
    .maybeSingle();

  if (error) {
    console.error(`[QhubApp] getProposal failed: ${error.message}`);
    return null;
  }

  return (data as ClassificationProposal | null) ?? null;
}

/** Mark a proposal consumed (single-use). Returns true if it transitioned. */
export async function markProposalConsumed(proposalId: string, env: Record<string, string | undefined>): Promise<void> {
  const sb = getSupabaseAdmin(env);
  const { error } = await sb
    .from('qhub_classification_proposals')
    .update({ status: 'CONSUMED' })
    .eq('proposal_id', proposalId)
    .eq('status', 'PENDING');

  if (error) {
    console.error(`[QhubApp] markProposalConsumed failed: ${error.message}`);
  }
}

// ─── Gate 03: policy snapshot persistence ─────────────────────────────────────

/** Atomically persist the current policy profile snapshot on the app record. */
export async function persistPolicyProfile(
  qhubAppId: string,
  profile: PolicyProfile,
  env: Record<string, string | undefined>,
): Promise<void> {
  const sb = getSupabaseAdmin(env);
  const { error } = await sb
    .from('qhub_applications')
    .update({
      policy_profile_id: profile.policy_profile_id,
      policy_profile_version: profile.policy_profile_version,
      policy_catalog_version: profile.policy_catalog_version,
      policy_profile: profile,
      policy_profile_hash: profile.policy_profile_hash,
      policy_status: profile.status,
      policy_assigned_at: profile.generated_at,
      policy_assigned_by: profile.generated_by,
    })
    .eq('qhub_app_id', qhubAppId);

  if (error) {
    console.error(`[QhubApp] persistPolicyProfile failed for ${qhubAppId}: ${error.message}`);
    return;
  }

  for (const [convId, record] of appCache.entries()) {
    if (record.qhub_app_id === qhubAppId) {
      appCache.delete(convId);
      break;
    }
  }
  console.log(
    `[QhubApp] policy profile persisted qhub_app_id=${qhubAppId} tier=${profile.risk_tier} v=${profile.policy_profile_version} status=${profile.status}`,
  );
}

/** Read the full persisted policy profile for a conversation's app (null until assigned). */
export async function getPolicyProfileByConversation(
  conversationId: string,
  orgId: string,
  env: Record<string, string | undefined>,
): Promise<PolicyProfile | null> {
  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_applications')
    .select('policy_profile')
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId)
    .maybeSingle();

  if (error) {
    console.error(`[QhubApp] getPolicyProfileByConversation failed: ${error.message}`);
    return null;
  }

  return (data?.policy_profile as PolicyProfile | null) ?? null;
}

/** Read the current persisted policy profile (null until assigned). */
export async function getPolicyProfile(
  qhubAppId: string,
  env: Record<string, string | undefined>,
): Promise<PolicyProfile | null> {
  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_applications')
    .select('policy_profile')
    .eq('qhub_app_id', qhubAppId)
    .maybeSingle();

  if (error) {
    console.error(`[QhubApp] getPolicyProfile failed for ${qhubAppId}: ${error.message}`);
    return null;
  }

  return (data?.policy_profile as PolicyProfile | null) ?? null;
}

/** Read the current policy profile + status for a conversation's app. */
export async function getPolicySnapshot(
  conversationId: string,
  orgId: string,
  env: Record<string, string | undefined>,
): Promise<{
  policy_profile_id: string | null;
  policy_profile_version: number | null;
  policy_profile_hash: string | null;
  policy_status: PolicyStatus | null;
} | null> {
  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_applications')
    .select('policy_profile_id, policy_profile_version, policy_profile_hash, policy_status')
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId)
    .maybeSingle();

  if (error) {
    console.error(`[QhubApp] getPolicySnapshot failed: ${error.message}`);
    return null;
  }

  return (data as any) ?? null;
}

/** Update just the policy status (e.g. ACKNOWLEDGED). */
export async function updatePolicyStatus(
  qhubAppId: string,
  status: PolicyStatus,
  env: Record<string, string | undefined>,
): Promise<void> {
  const sb = getSupabaseAdmin(env);
  const { error } = await sb.from('qhub_applications').update({ policy_status: status }).eq('qhub_app_id', qhubAppId);

  if (error) {
    console.error(`[QhubApp] updatePolicyStatus failed for ${qhubAppId}: ${error.message}`);
  } else {
    for (const [convId, record] of appCache.entries()) {
      if (record.qhub_app_id === qhubAppId) {
        appCache.delete(convId);
        break;
      }
    }
  }
}

/** AST-readable module authority classification (commercial-architecture.test.ts). */
export const __QHUB_MODULE_CLASSIFICATION = 'INTERNAL_SERVER_ONLY' as const;
