/**
 * QHUB Application Identity — SERVER ONLY
 * app/lib/qhub/qhub-app.server.ts
 *
 * Manages the permanent Quantex-owned identity for every AI-built application
 * that passes through QHUB Studio. This identity is independent of Bolt's
 * ephemeral identifiers (chatId, urlId, conversationId).
 *
 * KEY CONCEPTS:
 *   qhub_app_id — UUIDv4 generated by this module. This is the stable Quantex
 *                 identity and is the app_id sent to the Lambda in all events.
 *
 *   chain_id    — UUIDv4 returned by the Lambda after a successful CHAIN_GENESIS
 *                 event. Stored durably in Supabase. This replaces the in-memory
 *                 chainIdCache from prior versions, which was not durable across
 *                 process restart, redeployment, or Cloudflare isolate recycling.
 *
 * PERSISTENCE:
 *   Primary store: Supabase (qhub_applications table — see migrations/).
 *   In-memory cache: module-level Map for warm reads. The DB is always the
 *   source of truth; the cache is an optimization only.
 *
 * REQUIRED ENV VARS (server-side only):
 *   SUPABASE_URL              Quantex Supabase project URL
 *   SUPABASE_SERVICE_ROLE_KEY Service role key — bypasses RLS, never expose to browser
 */

import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { ClassificationResult, PersistedRiskTier } from './classification';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface QhubAppRecord {
  qhub_app_id: string;
  org_id: string;
  created_by: string;
  builder_engine: string;
  builder_project_id: string | null;
  conversation_id: string | null;
  workspace_id: string | null;
  chain_id: string | null;
  risk_tier: string;
  classification: ClassificationResult | null;
  governance_status: string;
  created_at: string;
  updated_at: string;
}

export interface CreateQhubAppParams {
  orgId: string;
  userId: string;
  conversationId: string;
  /** bolt.diy urlId — may be null initially, filled in once first artifact is created */
  builderProjectId?: string;
}

// ─── In-memory cache (optimization — DB is authoritative) ─────────────────────
// Keyed by conversationId → QhubAppRecord
// Invalidated on chain_id write and updated_at change.

const appCache = new Map<string, QhubAppRecord>();

// ─── Supabase client factory (service role — server only) ─────────────────────

function getSupabaseAdmin(env: Record<string, string | undefined>): SupabaseClient {
  const url = env.SUPABASE_URL ?? process.env.SUPABASE_URL ?? '';
  const serviceKey =
    env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_SERVICE_ROLE_KEY ?? '';

  if (!url || !serviceKey) {
    throw new Error(
      '[QhubApp] SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required for durable persistence.',
    );
  }

  return createClient(url, serviceKey, {
    auth: { persistSession: false },
  });
}

// ─── Create or retrieve existing QHUB app for a conversation ─────────────────

/**
 * Get or create the QHUB application record for a given conversation.
 *
 * Idempotent: if a record already exists for this conversationId, returns it.
 * Otherwise creates a new record with a fresh qhub_app_id.
 *
 * The returned qhub_app_id is the stable app_id to use in all Lambda events.
 */
export async function getOrCreateQhubApp(
  params: CreateQhubAppParams,
  env: Record<string, string | undefined>,
): Promise<QhubAppRecord> {
  const { conversationId, orgId, userId, builderProjectId } = params;

  // 1. Hot cache hit
  const cached = appCache.get(conversationId);
  if (cached) return cached;

  const sb = getSupabaseAdmin(env);

  // 2. DB lookup by conversationId
  const { data: existing, error: lookupErr } = await sb
    .from('qhub_applications')
    .select('*')
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId)
    .maybeSingle();

  if (lookupErr) {
    throw new Error(`[QhubApp] DB lookup failed: ${lookupErr.message}`);
  }

  if (existing) {
    // Update builderProjectId if it was null and now available
    if (!existing.builder_project_id && builderProjectId) {
      const { data: updated } = await sb
        .from('qhub_applications')
        .update({ builder_project_id: builderProjectId })
        .eq('qhub_app_id', existing.qhub_app_id)
        .select()
        .single();

      const record = (updated ?? existing) as QhubAppRecord;
      appCache.set(conversationId, record);
      return record;
    }

    appCache.set(conversationId, existing as QhubAppRecord);
    return existing as QhubAppRecord;
  }

  // 3. Create new record
  const { data: created, error: createErr } = await sb
    .from('qhub_applications')
    .insert({
      org_id: orgId,
      created_by: userId,
      builder_engine: 'qhub-studio',
      builder_project_id: builderProjectId ?? null,
      conversation_id: conversationId,
      governance_status: 'pending',
    })
    .select()
    .single();

  if (createErr || !created) {
    throw new Error(`[QhubApp] DB insert failed: ${createErr?.message ?? 'no data returned'}`);
  }

  const record = created as QhubAppRecord;
  appCache.set(conversationId, record);

  console.log(
    `[QhubApp] Created app record qhub_app_id=${record.qhub_app_id} for conversation=${conversationId}`,
  );

  return record;
}

// ─── Persist chain_id after successful genesis ─────────────────────────────────

/**
 * Store the chain_id returned by Lambda after a successful CHAIN_GENESIS event.
 * Marks governance_status = 'genesis_committed'.
 *
 * This is the authoritative write that replaces the in-memory chainIdCache.
 * Must be called immediately after Lambda returns chain_id.
 */
export async function persistChainId(
  qhubAppId: string,
  chainId: string,
  env: Record<string, string | undefined>,
): Promise<void> {
  const sb = getSupabaseAdmin(env);

  const { error } = await sb
    .from('qhub_applications')
    .update({ chain_id: chainId, governance_status: 'genesis_committed' })
    .eq('qhub_app_id', qhubAppId)
    .is('chain_id', null); // Only write once — chain_id is immutable after genesis

  if (error) {
    // Log but do not throw — the event was already written to Lambda/DynamoDB.
    // The chain is intact; only our local record is incomplete.
    console.error(
      `[QhubApp] Failed to persist chain_id for qhub_app_id=${qhubAppId}: ${error.message}`,
    );
    return;
  }

  // Invalidate cache entry so next read fetches the updated record
  for (const [convId, record] of appCache.entries()) {
    if (record.qhub_app_id === qhubAppId) {
      appCache.delete(convId);
      break;
    }
  }

  console.log(`[QhubApp] chain_id persisted for qhub_app_id=${qhubAppId}`);
}

// ─── Read chain_id (durable, with cache) ──────────────────────────────────────

/**
 * Retrieve the chain_id for a given conversationId.
 * Returns null if genesis has not yet been committed.
 *
 * Read order: memory cache → Supabase DB.
 */
export async function getChainId(
  conversationId: string,
  orgId: string,
  env: Record<string, string | undefined>,
): Promise<string | null> {
  // Cache hit
  const cached = appCache.get(conversationId);
  if (cached) return cached.chain_id;

  // DB read
  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_applications')
    .select('qhub_app_id, chain_id')
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId)
    .maybeSingle();

  if (error) {
    console.error(`[QhubApp] getChainId DB read failed: ${error.message}`);
    return null;
  }

  return data?.chain_id ?? null;
}

// ─── Update builderProjectId (called when urlId becomes available) ─────────────

/**
 * Update the builderProjectId (bolt.diy urlId) on an existing record.
 * Called from Chat.client.tsx when urlId is first set.
 */
export async function updateBuilderProjectId(
  conversationId: string,
  orgId: string,
  builderProjectId: string,
  env: Record<string, string | undefined>,
): Promise<void> {
  const sb = getSupabaseAdmin(env);
  const { error } = await sb
    .from('qhub_applications')
    .update({ builder_project_id: builderProjectId })
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId);

  if (error) {
    console.error(`[QhubApp] updateBuilderProjectId failed: ${error.message}`);
  } else {
    // Invalidate cache
    appCache.delete(conversationId);
  }
}

// ─── Gate 02: classification persistence ──────────────────────────────────────

/**
 * Persist the current classification and its risk tier on the app record.
 * The immutable ledger (CLASSIFICATION_ASSIGNED events) remains the authoritative
 * history; this row holds only the CURRENT classification for fast reads.
 * Marks governance_status = 'classified'.
 */
export async function persistClassification(
  qhubAppId: string,
  classification: ClassificationResult,
  env: Record<string, string | undefined>,
): Promise<void> {
  const sb = getSupabaseAdmin(env);

  // Write the tier first (columns that always exist) so subsequent events get
  // the real tier even if the classification JSONB column hasn't been migrated.
  const { error: tierErr } = await sb
    .from('qhub_applications')
    .update({ risk_tier: classification.risk_tier, governance_status: 'classified' })
    .eq('qhub_app_id', qhubAppId);

  if (tierErr) {
    console.error(`[QhubApp] persistClassification tier write failed for ${qhubAppId}: ${tierErr.message}`);
  }

  // Then the full snapshot (best-effort; requires the 20260725 migration).
  const { error: jsonErr } = await sb
    .from('qhub_applications')
    .update({ classification })
    .eq('qhub_app_id', qhubAppId);

  if (jsonErr) {
    console.error(
      `[QhubApp] persistClassification snapshot write failed for ${qhubAppId} (run the classification migration): ${jsonErr.message}`,
    );
  }

  // Invalidate cache so subsequent events read the new tier.
  for (const [convId, record] of appCache.entries()) {
    if (record.qhub_app_id === qhubAppId) {
      appCache.delete(convId);
      break;
    }
  }

  console.log(
    `[QhubApp] classification persisted qhub_app_id=${qhubAppId} risk_tier=${classification.risk_tier} v=${classification.classification_version}`,
  );
}

/** Read the current persisted classification (for versioning / gate checks). */
export async function getClassification(
  qhubAppId: string,
  env: Record<string, string | undefined>,
): Promise<ClassificationResult | null> {
  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_applications')
    .select('classification')
    .eq('qhub_app_id', qhubAppId)
    .maybeSingle();

  if (error) {
    console.error(`[QhubApp] getClassification failed for ${qhubAppId}: ${error.message}`);
    return null;
  }

  return (data?.classification as ClassificationResult | null) ?? null;
}

/**
 * Read the persisted risk tier for the app of a given conversation.
 * Returns 'UNCLASSIFIED' until a classification has been confirmed.
 * Used so genesis / AI_MODEL_INVOKED / gate events carry the REAL tier.
 */
export async function getPersistedRiskTier(
  conversationId: string,
  orgId: string,
  env: Record<string, string | undefined>,
): Promise<PersistedRiskTier> {
  const cached = appCache.get(conversationId);
  if (cached?.risk_tier) {
    return (cached.risk_tier as PersistedRiskTier) ?? 'UNCLASSIFIED';
  }

  const sb = getSupabaseAdmin(env);
  const { data, error } = await sb
    .from('qhub_applications')
    .select('risk_tier')
    .eq('conversation_id', conversationId)
    .eq('org_id', orgId)
    .maybeSingle();

  if (error) {
    console.error(`[QhubApp] getPersistedRiskTier failed: ${error.message}`);
    return 'UNCLASSIFIED';
  }

  return ((data?.risk_tier as PersistedRiskTier) ?? 'UNCLASSIFIED') || 'UNCLASSIFIED';
}
